### ISSUE TITLE
建议兼容MySql5.7，犹如Java8还是广泛使用的

### ISSUE THREAD

**Issue by gotoeasy** [zhaovincent/CXYGZL#1]
工作流部分也是，拆分成独立的单独的应用，考虑接口，方便接入其他系统

现如今，从0开发的项目太少，多数都是修修改改拼拼凑凑

**Comment by zhaovincent** [comment]
已改造 周末会发一版：支持mysql5.7 支持接口对接外部用户管理系统  可以加群沟通 https://www.cxygzl.com

**Comment by gotoeasy** [comment]
响应神速
